#!/bin/bash

set -x

export PYTHONPATH=$PWD:$PWD/probert:$PWD/curtin

cleanup () {
    jobsout=$(jobs -p)
    [ -n "$jobsout" ] && kill $jobsout
    echo
}

trap cleanup EXIT

rm -fr .subiquity

args=(--dry-run)
args+=(--bootloader uefi)

# args+=(--machine-config examples/simple.json)
# args+=(--machine-config examples/many-nics-and-disks.json.json)
# args+=(--autoinstall="")
args+=(--machine-config examples/win10.json)
# args+=(--machine-config ~/probert.json)

# args+=(--autoinstall examples/autoinstall.yaml)

python3 -m subiquity.cmd.server "${args[@]}"
