#!/bin/bash

set -x

rm -fr .subiquity

PYTHONPATH=$PWD:$PWD/probert:$PWD/curtin
export PYTHONPATH

args=(--dry-run)
args+=(--bootloader uefi)
# args+=(--bootloader bios)

# args+=(--machine-config examples/simple.json)
args+=(--machine-config examples/many-nics-and-disks.json)
# args+=(--machine-config examples/win10.json)
# args+=(--machine-config ~/probert.json)

# args+=(--autoinstall="")
# args+=(--autoinstall examples/autoinstall.yaml)

args+=(--source-catalog="install-sources.yaml")

python3 -m subiquity "${args[@]}"
