#!/bin/bash

set -u

headers=$(mktemp)
stderr=$(mktemp)

cleanup () {
    rm -f "$headers" "$stderr"
}

trap cleanup EXIT

data=$(curl --dump-header "$headers" --unix-socket .subiquity/socket $* \
       2> "$stderr")
ec=$?

status=$(head -n1 < "$headers" | awk '{print $2}')

if [ "$ec" = "0" -a "$status" = "200" ] ; then
    # when things look good, print headers and formatted data
    cat "$headers"
    echo "$data" | jq
else
    # only print stderr if curl exited with error
    [ "$ec" != "0" ] && cat "$stderr"
    cat "$headers"
    # show the raw data, likely not JSON
    echo "$data"
fi
